---
title: "OBTN alternative race/ethnicity plots"
output:
  html_document:
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F,
                      warning = F,
                      message = F)
```

```{r}
# Packages ----------------------------------------------------------------

library(tidyverse)
library(tigris)
library(here)
library(readxl)
library(janitor)
library(scales)
library(Cairo)

# Load functions ----------------------------------------------------------

source(here("R", "functions.R"))
source(here("R", "tfff-themes.R"))

# Update tfff_light_green

tfff_light_green <- "#CFDEB7"

```

Note: all plots done for Latino population


# By county by percentage within county

```{r include = F}


# Get OBTN data -----------------------------------------------------------

race_ethnicity_data <- read_excel(here("data", "obtn-by-county.xlsx"),
                                  sheet = "Race Ethnicity") %>% 
     clean_names() %>% 
     filter(geography != "Rural") %>% 
     filter(geography != "Urban") %>% 
     filter(geography != "Oregon") %>% 
     gather("population", "pct", -geography) %>% 
     mutate(population = case_when(
          population == "percentage_of_population_white_non_latino" ~ "White",
          population == "percentage_of_population_black_non_latino" ~ "African American",
          population == "percentage_of_population_asian_non_latino" ~ "Asian",
          population == "percentage_of_population_american_indian_or_alaska_native_non_latino" ~ "Am Indian/Alaska Native",
          population == "percentage_of_population_native_hawaiian_pacific_islander_non_latino" ~ "Native Hawaiian/Pacific Islander",
          population == "percentage_of_population_multi_racial_non_latino" ~ "Multiracial",
          population == "percentage_of_population_other_race_non_latino" ~ "Other Race",
          population == "percentage_of_population_latino" ~ "Latino"
     )) %>% 
     group_by(population) %>% 
     mutate(tertile = ntile(pct, 3)) %>% 
     mutate(tertile_numeric = as.numeric(tertile)) %>% 
     ungroup()

race_ethnicity_groups <- race_ethnicity_data %>% 
     distinct(population) %>% 
     pull()


# Get geodata -------------------------------------------------------------

by_county_by_pct_within_county <- dk_oregon_counties_geodata() %>% 
     left_join(race_ethnicity_data, by = c("name" = "geography")) 

oregon_counties_geodata <- dk_oregon_counties_geodata() %>% 
     left_join(race_ethnicity_data, by = c("name" = "geography")) 


# Plot --------------------------------------------------------------------

dk_make_race_ethnicity_map <- function(race_ethnicity_group) {
     
     oregon_counties_geodata_filtered <- by_county_by_pct_within_county %>% 
          filter(population == race_ethnicity_group)
     
     ggplot(oregon_counties_geodata_filtered) +
          geom_sf(aes(fill = pct),
                  # fill =  tfff_dark_green,
                  color = "white") +
          coord_sf(datum = NA) +
          scale_fill_gradient(low = tfff_light_green,
                              high = tfff_dark_green,
                              labels = percent_format(1)) +
          tfff_map_theme +
          theme(legend.position = "bottom") +
          guides(fill = guide_legend(nrow = 1))
     
}



```

```{r}
dk_make_race_ethnicity_map("Latino")
```

# By county by number of people

```{r include = F}

county_populations <- read_excel(here("data", "race-ethnicity-by-tract.xlsx"),
                                 skip = 2) %>% 
     clean_names() %>% 
     slice(2:37) %>% 
     select(geography:estimate_total) %>% 
     mutate(geography = str_remove(geography, " County, Oregon"))

by_county_by_number_within_county <- dk_oregon_counties_geodata() %>% 
     left_join(race_ethnicity_data, by = c("name" = "geography")) %>% 
     left_join(county_populations, by = c("name" = "geography")) %>% 
     mutate(group_population = pct * estimate_total)

```

```{r}
by_county_by_number_within_county_filtered <- by_county_by_number_within_county %>% 
     filter(population == "Latino")

ggplot(by_county_by_number_within_county_filtered) +
     geom_sf(aes(fill = group_population),
             # fill =  tfff_dark_green,
             color = "white") +
     coord_sf(datum = NA) +
     scale_fill_gradient(low = tfff_light_green,
                         high = tfff_dark_green) +
     tfff_map_theme +
     theme(legend.position = "bottom") +
     guides(fill = guide_legend(nrow = 1))
```




# By Census tract by percentage within county


```{r include = F}
race_ethnicity_by_tract <- read_excel(here("data", "race-ethnicity-by-tract.xlsx"),
                                      skip = 2) %>% 
     clean_names() %>% 
     filter(str_length(id2) > 5) %>% # Drop all Oregon and county data
     select(-contains("margin")) %>% 
     select(-estimate_not_hispanic_or_latino) %>% 
     select(id:geography, estimate_total:estimate_hispanic_or_latino) %>% 
     gather("group", "number", -c(id, id2, geography)) %>% 
     mutate(id2 = as.character(id2)) %>% 
     filter(group != "estimate_total") %>% 
     group_by(id2) %>% 
     mutate(pct = prop.table(number)) %>% 
     ungroup()

oregon_tracts_geodata <- tracts("OR", cb = T, class="sf") %>% 
     clean_names() %>% 
     left_join(race_ethnicity_by_tract, by = c("geoid" = "id2")) %>% 
     filter(str_detect(group, "estimate_hispanic_or_latino"))


```

```{r}
ggplot(oregon_tracts_geodata) +
     geom_sf(aes(fill = pct),
             color = "transparent",
             size = .1) +
     geom_sf(data = oregon_counties_geodata,
             fill =  "transparent",
             color = "white",
             size = 0.2) +
     coord_sf(datum = NA) +
     scale_fill_gradient(low = tfff_light_green,
                         high = tfff_dark_green,
                         labels = percent_format(1)) +
     tfff_map_theme +
     theme(legend.position = "bottom") +
     guides(fill = guide_legend(nrow = 1))
```



# By Census tract by number of people

```{r include = F}

tract_total_populations <- read_excel(here("data", "race-ethnicity-by-tract.xlsx"),
                                                                 skip = 2) %>% 
     clean_names() %>% 
     filter(str_detect(geography, "Tract")) %>% 
     select(id2, estimate_total) %>% 
     mutate(id2 = as.character(id2))

by_tract_by_number <- oregon_tracts_geodata %>% 
     left_join(tract_total_populations, by = c("geoid" = "id2")) %>% 
     mutate(group_population = pct * estimate_total) 

```

```{r}
ggplot(by_tract_by_number) +
     geom_sf(aes(fill = group_population),
             color = "transparent",
             size = .1) +
     geom_sf(data = oregon_counties_geodata,
             fill =  "transparent",
             color = "white",
             size = 0.2) +
     coord_sf(datum = NA) +
     scale_fill_gradient(low = tfff_light_green,
                         high = tfff_dark_green) +
     tfff_map_theme +
     theme(legend.position = "bottom") +
     guides(fill = guide_legend(nrow = 1))
```


